import 'package:watchly/movies/domain/entities/movie_entity.dart';

List<MovieEntity> movies = [
  MovieEntity(
    id: 10,
    backdropPath: "/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg",
    genreIds: [1, 2, 3],
    overview: "Test overview",
    posterPath: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    releaseDate: "2025-12-2",
    title: "I Still Know What You Did Last Summer",
    voteAverage: 3.9,
  ),
  MovieEntity(
    id: 20,
    backdropPath: "/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg",
    genreIds: [1, 2, 3],
    overview: "Test overview",
    posterPath: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    releaseDate: "2025-12-2",
    title: "title2",
    voteAverage: 3.9,
  ),
  MovieEntity(
    id: 30,
    backdropPath: "/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg",
    genreIds: [1, 2, 3],
    overview: "Test overview",
    posterPath: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    releaseDate: "2025-12-2",
    title: "title3",
    voteAverage: 3.9,
  ),
  MovieEntity(
    id: 40,
    backdropPath: "/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg",
    genreIds: [1, 2, 3],
    overview: "Test overview",
    posterPath: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    releaseDate: "2025-12-2",
    title: "title4",
    voteAverage: 3.9,
  ),
  MovieEntity(
    id: 50,
    backdropPath: "/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg",
    genreIds: [1, 2, 3],
    overview: "Test overview",
    posterPath: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    releaseDate: "2025-12-2",
    title: "title5",
    voteAverage: 3.9,
  ),
  MovieEntity(
    id: 1,
    backdropPath: "/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg",
    genreIds: [1, 2, 3],
    overview: "Test overview",
    posterPath: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    releaseDate: "2025-12-2",
    title: "title6",
    voteAverage: 3.9,
  ),
  MovieEntity(
    id: 2,
    backdropPath: "/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg",
    genreIds: [1, 2, 3],
    overview: "Test overview",
    posterPath: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    releaseDate: "2025-12-2",
    title: "title7",
    voteAverage: 3.9,
  ),
  MovieEntity(
    id: 3,
    backdropPath: "/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg",
    genreIds: [1, 2, 3],
    overview: "Test overview",
    posterPath: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    releaseDate: "2025-12-2",
    title: "title8",
    voteAverage: 3.9,
  ),
  MovieEntity(
    id: 4,
    backdropPath: "/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg",
    genreIds: [1, 2, 3],
    overview: "Test overview",
    posterPath: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    releaseDate: "2025-12-2",
    title: "title9",
    voteAverage: 3.9,
  ),
  MovieEntity(
    id: 5,
    backdropPath: "/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg",
    genreIds: [1, 2, 3],
    overview: "Test overview",
    posterPath: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    releaseDate: "2025-12-2",
    title: "title10",
    voteAverage: 3.9,
  ),
];
